const fs = require('fs');
const indiaSvgMap = require('@svg-maps/india').default;

const svgPaths = {};
indiaSvgMap.locations.forEach(loc => {
  svgPaths[loc.id] = loc.path;
});

const content = `export interface IndiaRegionItem {
  id: string;
  type: 'state' | 'ut';
  number: number;
  nameEn: string;
  nameHi: string;
  code: string;
  capitalEn: string;
  capitalHi: string;
  zone: 'North' | 'South' | 'East' | 'West' | 'Central' | 'North-East' | 'Islands';
  zoneHi: string;
  famousForEn: string;
  famousForHi: string;
  funFactEn: string;
  funFactHi: string;
  languageEn: string;
  languageHi: string;
  icon: string;
  color: string;
  svgPath: string;
  center: { x: number; y: number };
  isIslandOrTiny?: boolean;
}

export const INDIA_STATES: IndiaRegionItem[] = [
  {
    id: 'andhra-pradesh',
    type: 'state',
    number: 1,
    nameEn: 'Andhra Pradesh',
    nameHi: 'आंध्र प्रदेश',
    code: 'AP',
    capitalEn: 'Amaravati',
    capitalHi: 'अमरावती',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'Tirupati Balaji Temple, Kuchipudi Dance, Spices & Chillies',
    famousForHi: 'तिरुपति बालाजी मंदिर, कुचिपुड़ी नृत्य, मिर्च व मसाले',
    funFactEn: 'Andhra Pradesh has the second-longest coastline in India (974 km)!',
    funFactHi: 'आंध्र प्रदेश की तटरेखा भारत में दूसरी सबसे लंबी (974 किमी) है!',
    languageEn: 'Telugu',
    languageHi: 'तेलुगु',
    icon: '🛕',
    color: '#0284c7',
    svgPath: ${JSON.stringify(svgPaths['ap'])},
    center: { x: 263, y: 500 }
  },
  {
    id: 'arunachal-pradesh',
    type: 'state',
    number: 2,
    nameEn: 'Arunachal Pradesh',
    nameHi: 'अरुणाचल प्रदेश',
    code: 'AR',
    capitalEn: 'Itanagar',
    capitalHi: 'ईटानगर',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Land of Rising Sun, Tawang Monastery, Orchids',
    famousForHi: 'उगते सूरज की भूमि, तवांग बौद्ध मठ, सुंदर आर्किड फूल',
    funFactEn: 'India sees its very first sunrise in Dong Village of Arunachal Pradesh!',
    funFactHi: 'भारत में सूर्य की पहली किरण अरुणाचल प्रदेश के डोंग गांव में पड़ती है!',
    languageEn: 'English, Nyishi',
    languageHi: 'अंग्रेजी, निशि',
    icon: '🌅',
    color: '#059669',
    svgPath: ${JSON.stringify(svgPaths['ar'])},
    center: { x: 550, y: 224 }
  },
  {
    id: 'assam',
    type: 'state',
    number: 3,
    nameEn: 'Assam',
    nameHi: 'असम',
    code: 'AS',
    capitalEn: 'Dispur',
    capitalHi: 'दिसपुर',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'One-horned Rhino, Assam Tea, Bihu Dance, Brahmaputra River',
    famousForHi: 'एक सींग वाला गैंडा, असम चाय, बिहू नृत्य, ब्रह्मपुत्र नदी',
    funFactEn: 'Assam produces over 50% of all tea grown in India!',
    funFactHi: 'भारत की कुल चाय उत्पादन का 50% से अधिक हिस्सा असम में पैदा होता है!',
    languageEn: 'Assamese',
    languageHi: 'असमिया',
    icon: '🦏',
    color: '#10b981',
    svgPath: ${JSON.stringify(svgPaths['as'])},
    center: { x: 516, y: 271 }
  },
  {
    id: 'bihar',
    type: 'state',
    number: 4,
    nameEn: 'Bihar',
    nameHi: 'बिहार',
    code: 'BR',
    capitalEn: 'Patna',
    capitalHi: 'पटना',
    zone: 'East',
    zoneHi: 'पूर्वी भारत',
    famousForEn: 'Nalanda University, Bodh Gaya, Madhubani Art, Litti Chokha',
    famousForHi: 'नालंदा विश्वविद्यालय, बोधगया, मधुबनी पेंटिंग, लिट्टी चोखा',
    funFactEn: 'Ancient Nalanda was the world’s first residential university!',
    funFactHi: 'प्राचीन नालंदा विश्वविद्यालय विश्व का पहला आवासीय विश्वविद्यालय था!',
    languageEn: 'Hindi, Maithili',
    languageHi: 'हिन्दी, मैथिली',
    icon: '🏛️',
    color: '#f59e0b',
    svgPath: ${JSON.stringify(svgPaths['br'])},
    center: { x: 369, y: 275 }
  },
  {
    id: 'chhattisgarh',
    type: 'state',
    number: 5,
    nameEn: 'Chhattisgarh',
    nameHi: 'छत्तीसगढ़',
    code: 'CG',
    capitalEn: 'Raipur',
    capitalHi: 'रायपुर',
    zone: 'Central',
    zoneHi: 'मध्य भारत',
    famousForEn: 'Chitrakote Waterfalls, Bastar Tribal Art',
    famousForHi: 'चित्रकोट जलप्रपात (भारत का नियाग्रा), बस्तर आदिवासी कला',
    funFactEn: 'Chitrakote Falls on Indravati River is the widest waterfall in India!',
    funFactHi: 'इंद्रावती नदी पर स्थित चित्रकोट जलप्रपात भारत का सबसे चौड़ा जलप्रपात है!',
    languageEn: 'Chhattisgarhi, Hindi',
    languageHi: 'छत्तीसगढ़ी, हिन्दी',
    icon: '🌊',
    color: '#84cc16',
    svgPath: ${JSON.stringify(svgPaths['ct'])},
    center: { x: 296, y: 388 }
  },
  {
    id: 'goa',
    type: 'state',
    number: 6,
    nameEn: 'Goa',
    nameHi: 'गोवा',
    code: 'GA',
    capitalEn: 'Panaji',
    capitalHi: 'पणजी',
    zone: 'West',
    zoneHi: 'पश्चिमी भारत',
    famousForEn: 'Beaches, Dudhsagar Waterfalls, Portuguese Architecture',
    famousForHi: 'सुंदर समुद्री तट, दूधसागर जलप्रपात, पुर्तगाली धरोहर',
    funFactEn: 'Goa is the smallest state in India by area!',
    funFactHi: 'क्षेत्रफल के हिसाब से गोवा भारत का सबसे छोटा राज्य है!',
    languageEn: 'Konkani',
    languageHi: 'कोंकणी',
    icon: '🏖️',
    color: '#06b6d4',
    svgPath: ${JSON.stringify(svgPaths['ga'])},
    center: { x: 122, y: 512 }
  },
  {
    id: 'gujarat',
    type: 'state',
    number: 7,
    nameEn: 'Gujarat',
    nameHi: 'गुजरात',
    code: 'GJ',
    capitalEn: 'Gandhinagar',
    capitalHi: 'गांधीनगर',
    zone: 'West',
    zoneHi: 'पश्चिमी भारत',
    famousForEn: 'Gir Asiatic Lions, Statue of Unity, Rann of Kutch, Garba',
    famousForHi: 'गिर के एशियाई शेर, स्टैच्यू ऑफ यूनिटी, कच्छ का रण, गरबा',
    funFactEn: 'Statue of Unity (182m) in Gujarat is the tallest statue in the world!',
    funFactHi: 'गुजरात में स्टैच्यू ऑफ यूनिटी (182 मीटर) दुनिया की सबसे ऊंची मूर्ति है!',
    languageEn: 'Gujarati',
    languageHi: 'गुजराती',
    icon: '🦁',
    color: '#eab308',
    svgPath: ${JSON.stringify(svgPaths['gj'])},
    center: { x: 66, y: 355 }
  },
  {
    id: 'haryana',
    type: 'state',
    number: 8,
    nameEn: 'Haryana',
    nameHi: 'हरियाणा',
    code: 'HR',
    capitalEn: 'Chandigarh',
    capitalHi: 'चंडीगढ़',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Kurukshetra, Agriculture, Sports Champions',
    famousForHi: 'कुरुक्षेत्र (महाभारत की भूमि), कृषि, कुश्ती व खेल चैंपियन',
    funFactEn: 'Haryana produces maximum sports medal winners for India in Olympics!',
    funFactHi: 'हरियाणा भारत के लिए ओलंपिक में सर्वाधिक खेल पदक जीतने वाला राज्य है!',
    languageEn: 'Haryanvi, Hindi',
    languageHi: 'हरियाणवी, हिन्दी',
    icon: '🌾',
    color: '#a855f7',
    svgPath: ${JSON.stringify(svgPaths['hr'])},
    center: { x: 164, y: 195 }
  },
  {
    id: 'himachal-pradesh',
    type: 'state',
    number: 9,
    nameEn: 'Himachal Pradesh',
    nameHi: 'हिमाचल प्रदेश',
    code: 'HP',
    capitalEn: 'Shimla',
    capitalHi: 'शिमला',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Apple Orchards, Snow Peaks, Shimla Toy Train, Manali Valley',
    famousForHi: 'सेब के बागान, बर्फ से ढकी चोटियाँ, शिमला टॉय ट्रेन, मनाली घाटी',
    funFactEn: 'Kalka-Shimla Toy Train is a UNESCO World Heritage railway site!',
    funFactHi: 'कालका-शिमला टॉय ट्रेन यूनेस्को विश्व धरोहर रेलवे स्थल है!',
    languageEn: 'Hindi, Pahari',
    languageHi: 'हिन्दी, पहाड़ी',
    icon: '🏔️',
    color: '#3b82f6',
    svgPath: ${JSON.stringify(svgPaths['hp'])},
    center: { x: 191, y: 133 }
  },
  {
    id: 'jharkhand',
    type: 'state',
    number: 10,
    nameEn: 'Jharkhand',
    nameHi: 'झारखंड',
    code: 'JH',
    capitalEn: 'Ranchi',
    capitalHi: 'रांची',
    zone: 'East',
    zoneHi: 'पूर्वी भारत',
    famousForEn: 'Hundru Waterfalls, Mineral Hub, MS Dhoni Hometown',
    famousForHi: 'हुंदरू जलप्रपात, खनिज व कोयला भंडार, एमएस धोनी का शहर',
    funFactEn: 'Jharkhand contains over 40% of India’s total mineral resources!',
    funFactHi: 'झारखंड में भारत के कुल खनिज संसाधनों का 40% से अधिक हिस्सा मौजूद है!',
    languageEn: 'Hindi, Santhali',
    languageHi: 'हिन्दी, संथाली',
    icon: '💎',
    color: '#d97706',
    svgPath: ${JSON.stringify(svgPaths['jh'])},
    center: { x: 366, y: 327 }
  },
  {
    id: 'karnataka',
    type: 'state',
    number: 11,
    nameEn: 'Karnataka',
    nameHi: 'कर्नाटक',
    code: 'KA',
    capitalEn: 'Bengaluru',
    capitalHi: 'बेंगलुरु',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'Silicon Valley Bengaluru, Mysore Palace, Hampi Ruins',
    famousForHi: 'सिलिकॉन वैली बेंगलुरु, मैसूर महल, हम्पी स्मारक, कॉफी बागान',
    funFactEn: 'Bengaluru is known as the Silicon Valley of India and Space City!',
    funFactHi: 'बेंगलुरु को भारत की सिलिकॉन वैली और स्पेस सिटी कहा जाता है!',
    languageEn: 'Kannada',
    languageHi: 'कन्नड़',
    icon: '🏰',
    color: '#6366f1',
    svgPath: ${JSON.stringify(svgPaths['ka'])},
    center: { x: 171, y: 519 }
  },
  {
    id: 'kerala',
    type: 'state',
    number: 12,
    nameEn: 'Kerala',
    nameHi: 'केरल',
    code: 'KL',
    capitalEn: 'Thiruvananthapuram',
    capitalHi: 'तिरुवनंतपुरम',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'God’s Own Country, Backwaters, Kathakali, Ayurveda',
    famousForHi: 'ईश्वर का अपना देश (God’s Own Country), बैकवाटर, कथकली, आयुर्वेद',
    funFactEn: 'Kerala has the highest literacy rate (96%+) in India!',
    funFactHi: 'केरल में भारत की उच्चतम साक्षरता दर (96%+ से अधिक) है!',
    languageEn: 'Malayalam',
    languageHi: 'मलयालम',
    icon: '🌴',
    color: '#10b981',
    svgPath: ${JSON.stringify(svgPaths['kl'])},
    center: { x: 166, y: 615 }
  },
  {
    id: 'madhya-pradesh',
    type: 'state',
    number: 13,
    nameEn: 'Madhya Pradesh',
    nameHi: 'मध्य प्रदेश',
    code: 'MP',
    capitalEn: 'Bhopal',
    capitalHi: 'भोपाल',
    zone: 'Central',
    zoneHi: 'मध्य भारत',
    famousForEn: 'Heart of India, Tiger State, Khajuraho, Sanchi Stupa',
    famousForHi: 'भारत का हृदय (Heart of India), टाइगर स्टेट, खजुराहो, सांची स्तूप',
    funFactEn: 'Madhya Pradesh has 6 tiger reserves and largest forest cover!',
    funFactHi: 'मध्य प्रदेश में 6 टाइगर रिजर्व हैं और भारत में सबसे बड़ा वन क्षेत्र है!',
    languageEn: 'Hindi',
    languageHi: 'हिन्दी',
    icon: '🐅',
    color: '#f97316',
    svgPath: ${JSON.stringify(svgPaths['mp'])},
    center: { x: 214, y: 319 }
  },
  {
    id: 'maharashtra',
    type: 'state',
    number: 14,
    nameEn: 'Maharashtra',
    nameHi: 'महाराष्ट्र',
    code: 'MH',
    capitalEn: 'Mumbai',
    capitalHi: 'मुंबई',
    zone: 'West',
    zoneHi: 'पश्चिमी भारत',
    famousForEn: 'Mumbai Bollywood, Shivaji Forts, Ajanta Ellora Caves',
    famousForHi: 'मुंबई बॉलीवुड, छत्रपति शिवाजी महाराज के किले, अजंता-एलोरा गुफाएं',
    funFactEn: 'Mumbai is the financial capital of India and home to Bollywood!',
    funFactHi: 'मुंबई भारत की आर्थिक राजधानी और बॉलीवुड सिनेमा का केंद्र है!',
    languageEn: 'Marathi',
    languageHi: 'मराठी',
    icon: '🎬',
    color: '#ef4444',
    svgPath: ${JSON.stringify(svgPaths['mh'])},
    center: { x: 180, y: 435 }
  },
  {
    id: 'manipur',
    type: 'state',
    number: 15,
    nameEn: 'Manipur',
    nameHi: 'मणिपुर',
    code: 'MN',
    capitalEn: 'Imphal',
    capitalHi: 'इम्फाल',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Loktak Floating Lake, Keibul Lamjao Park, Manipuri Dance',
    famousForHi: 'लोकटक तैरती झील, कीबुल लामजाओ नेशनल पार्क, मणिपुरी नृत्य',
    funFactEn: 'Keibul Lamjao in Manipur is the world’s only floating national park!',
    funFactHi: 'मणिपुर में कीबुल लामजाओ विश्व का एकमात्र तैरता हुआ राष्ट्रीय उद्यान है!',
    languageEn: 'Manipuri (Meitei)',
    languageHi: 'मणिपुरी',
    icon: '🌸',
    color: '#ec4899',
    svgPath: ${JSON.stringify(svgPaths['mn'])},
    center: { x: 537, y: 301 }
  },
  {
    id: 'meghalaya',
    type: 'state',
    number: 16,
    nameEn: 'Meghalaya',
    nameHi: 'मेघालय',
    code: 'ML',
    capitalEn: 'Shillong',
    capitalHi: 'शिलांग',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Abode of Clouds, Living Root Bridges, Mawsynram',
    famousForHi: 'बादलों का घर, जीवित जड़ों के पुल, मौसिनराम',
    funFactEn: 'Mawsynram in Meghalaya gets the highest rainfall in the world!',
    funFactHi: 'मेघालय के मौसिनराम में दुनिया की सबसे ज्यादा बारिश होती है!',
    languageEn: 'English, Khasi, Garo',
    languageHi: 'अंग्रेजी, खासी, गारो',
    icon: '🌧️',
    color: '#0284c7',
    svgPath: ${JSON.stringify(svgPaths['ml'])},
    center: { x: 484, y: 283 }
  },
  {
    id: 'mizoram',
    type: 'state',
    number: 17,
    nameEn: 'Mizoram',
    nameHi: 'मिज़ोरम',
    code: 'MZ',
    capitalEn: 'Aizawl',
    capitalHi: 'आइजोल',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Blue Mountains, Cheraw Bamboo Dance, Forests',
    famousForHi: 'नीले पर्वतों की भूमि, चेरॉ बांस नृत्य, घने हरे-भरे जंगल',
    funFactEn: 'Mizoram is covered with 85%+ forest area and bamboo groves!',
    funFactHi: 'मिज़ोरम का 85% से अधिक हिस्सा घने वनों और बांस के जंगलों से घिरा है!',
    languageEn: 'Mizo, English',
    languageHi: 'मिज़ो, अंग्रेजी',
    icon: '🎋',
    color: '#14b8a6',
    svgPath: ${JSON.stringify(svgPaths['mz'])},
    center: { x: 516, y: 337 }
  },
  {
    id: 'nagaland',
    type: 'state',
    number: 18,
    nameEn: 'Nagaland',
    nameHi: 'नागालैंड',
    code: 'NL',
    capitalEn: 'Kohima',
    capitalHi: 'कोहिमा',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Hornbill Festival, Tribal Culture, Naga Hills',
    famousForHi: 'हॉर्नबिल महोत्सव, जनजातीय संस्कृति, नागा पहाड़ियां',
    funFactEn: 'Hornbill Festival is known as the Festival of Festivals in India!',
    funFactHi: 'हॉर्नबिल महोत्सव को भारत में त्योहारों का त्योहार कहा जाता है!',
    languageEn: 'English',
    languageHi: 'अंग्रेजी',
    icon: '🦚',
    color: '#f59e0b',
    svgPath: ${JSON.stringify(svgPaths['nl'])},
    center: { x: 546, y: 270 }
  },
  {
    id: 'odisha',
    type: 'state',
    number: 19,
    nameEn: 'Odisha',
    nameHi: 'ओडिशा',
    code: 'OD',
    capitalEn: 'Bhubaneswar',
    capitalHi: 'भुवनेश्वर',
    zone: 'East',
    zoneHi: 'पूर्वी भारत',
    famousForEn: 'Puri Jagannath Temple, Konark Sun Temple, Chilika Lake',
    famousForHi: 'पुरी जगन्नाथ मंदिर, कोणार्क सूर्य मंदिर, चिल्का झील',
    funFactEn: 'Konark Sun Temple is built in the shape of a massive stone chariot!',
    funFactHi: 'कोणार्क का सूर्य मंदिर पत्थर से बने एक विशाल रथ के आकार में निर्मित है!',
    languageEn: 'Odia',
    languageHi: 'ओडिया',
    icon: '🛕',
    color: '#8b5cf6',
    svgPath: ${JSON.stringify(svgPaths['or'])},
    center: { x: 340, y: 405 }
  },
  {
    id: 'punjab',
    type: 'state',
    number: 20,
    nameEn: 'Punjab',
    nameHi: 'पंजाब',
    code: 'PB',
    capitalEn: 'Chandigarh',
    capitalHi: 'चंडीगढ़',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Golden Temple Amritsar, Bhangra Dance, Land of Five Rivers',
    famousForHi: 'स्वर्ण मंदिर अमृतसर, भांगड़ा नृत्य, पांच नदियों की भूमि',
    funFactEn: 'Golden Temple serves free hot meals (Langar) to 100,000+ people daily!',
    funFactHi: 'अमृतसर का स्वर्ण मंदिर प्रतिदिन 1,00,000 से अधिक लोगों को मुफ्त लंगर कराता है!',
    languageEn: 'Punjabi',
    languageHi: 'पंजाबी',
    icon: 'ੴ',
    color: '#eab308',
    svgPath: ${JSON.stringify(svgPaths['pb'])},
    center: { x: 151, y: 152 }
  },
  {
    id: 'rajasthan',
    type: 'state',
    number: 21,
    nameEn: 'Rajasthan',
    nameHi: 'राजस्थान',
    code: 'RJ',
    capitalEn: 'Jaipur',
    capitalHi: 'जयपुर',
    zone: 'West',
    zoneHi: 'पश्चिमी भारत',
    famousForEn: 'Thar Desert, Forts & Palaces, Pink City Jaipur, Ghoomar Dance',
    famousForHi: 'थार मरुस्थल, भव्य किले व महल, पिंक सिटी जयपुर, घूमर नृत्य',
    funFactEn: 'Rajasthan is the largest state in India by total land area!',
    funFactHi: 'क्षेत्रफल के हिसाब से राजस्थान भारत का सबसे बड़ा राज्य है!',
    languageEn: 'Hindi, Rajasthani',
    languageHi: 'हिन्दी, राजस्थानी',
    icon: '🐪',
    color: '#f97316',
    svgPath: ${JSON.stringify(svgPaths['rj'])},
    center: { x: 119, y: 257 }
  },
  {
    id: 'sikkim',
    type: 'state',
    number: 22,
    nameEn: 'Sikkim',
    nameHi: 'सिक्किम',
    code: 'SK',
    capitalEn: 'Gangtok',
    capitalHi: 'गंगटोक',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Mount Kanchenjunga, Organic State, Monasteries',
    famousForHi: 'कंचनजंगा पर्वत (विश्व की 3री ऊंची चोटी), 100% जैविक राज्य',
    funFactEn: 'Sikkim is India’s very first 100% organic farming state!',
    funFactHi: 'सिक्किम भारत का सबसे पहला 100% जैविक खेती करने वाला राज्य है!',
    languageEn: 'Nepali, Bhutia, Lepcha',
    languageHi: 'नेपाली, भूटिया, लेप्चा',
    icon: '🏔️',
    color: '#06b6d4',
    svgPath: ${JSON.stringify(svgPaths['sk'])},
    center: { x: 425, y: 235 }
  },
  {
    id: 'tamil-nadu',
    type: 'state',
    number: 23,
    nameEn: 'Tamil Nadu',
    nameHi: 'तमिलनाडु',
    code: 'TN',
    capitalEn: 'Chennai',
    capitalHi: 'चेन्नई',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'Dravidian Temples, Bharatanatyam, Kanchipuram Silk',
    famousForHi: 'द्रविड़ शैली के मंदिर, भरतनाट्यम नृत्य, कांजीवरम सिल्क साड़ी',
    funFactEn: 'Tamil language is one of the world’s oldest classical languages!',
    funFactHi: 'तमिल भाषा विश्व की सबसे प्राचीनतम जीवित भाषाओं में से एक है!',
    languageEn: 'Tamil',
    languageHi: 'तमिल',
    icon: '🛕',
    color: '#ef4444',
    svgPath: ${JSON.stringify(svgPaths['tn'])},
    center: { x: 211, y: 609 }
  },
  {
    id: 'telangana',
    type: 'state',
    number: 24,
    nameEn: 'Telangana',
    nameHi: 'तेलंगाना',
    code: 'TG',
    capitalEn: 'Hyderabad',
    capitalHi: 'हैदराबाद',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'Charminar, Hyderabadi Biryani, Ramoji Film City',
    famousForHi: 'चारमीनार, हैदराबादी बिरयानी, रामोजी फिल्म सिटी, आईटी पार्क',
    funFactEn: 'Ramoji Film City in Hyderabad is the largest film studio complex in the world!',
    funFactHi: 'हैदराबाद का रामोजी फिल्म सिटी दुनिया का सबसे बड़ा फिल्म स्टूडियो परिसर है!',
    languageEn: 'Telugu, Urdu',
    languageHi: 'तेलुगु, उर्दू',
    icon: '🕌',
    color: '#3b82f6',
    svgPath: ${JSON.stringify(svgPaths['tg'])},
    center: { x: 237, y: 457 }
  },
  {
    id: 'tripura',
    type: 'state',
    number: 25,
    nameEn: 'Tripura',
    nameHi: 'त्रिपुरा',
    code: 'TR',
    capitalEn: 'Agartala',
    capitalHi: 'अगरतला',
    zone: 'North-East',
    zoneHi: 'पूर्वोत्तर भारत',
    famousForEn: 'Ujjayanta Palace, Neermahal Water Palace, Bamboo Handicrafts',
    famousForHi: 'उज्जयंत पैलेस, नीरमहल जल महल, बांस के सुंदर उत्पाद',
    funFactEn: 'Neermahal is the largest water palace in Northeast India!',
    funFactHi: 'नीरमहल पूर्वोत्तर भारत का सबसे बड़ा जल महल है!',
    languageEn: 'Kokborok, Bengali',
    languageHi: 'कोकबोरोक, बंगाली',
    icon: '🏰',
    color: '#ec4899',
    svgPath: ${JSON.stringify(svgPaths['tr'])},
    center: { x: 493, y: 325 }
  },
  {
    id: 'uttar-pradesh',
    type: 'state',
    number: 26,
    nameEn: 'Uttar Pradesh',
    nameHi: 'उत्तर प्रदेश',
    code: 'UP',
    capitalEn: 'Lucknow',
    capitalHi: 'लखनऊ',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Taj Mahal Agra, Holy Varanasi Ghats, Ayodhya Ram Mandir',
    famousForHi: 'ताजमहल आगरा, पवित्र वाराणसी घाट, अयोध्या राम मंदिर',
    funFactEn: 'Uttar Pradesh is the most populous state in India!',
    funFactHi: 'उत्तर प्रदेश भारत में सबसे अधिक जनसंख्या वाला राज्य है!',
    languageEn: 'Hindi, Urdu',
    languageHi: 'हिन्दी, उर्दू',
    icon: '🕌',
    color: '#f59e0b',
    svgPath: ${JSON.stringify(svgPaths['up'])},
    center: { x: 265, y: 245 }
  },
  {
    id: 'uttarakhand',
    type: 'state',
    number: 27,
    nameEn: 'Uttarakhand',
    nameHi: 'उत्तराखंड',
    code: 'UK',
    capitalEn: 'Dehradun',
    capitalHi: 'देहरादून',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Land of Gods, Kedarnath, Badrinath, Jim Corbett Park',
    famousForHi: 'देवभूमि, केदारनाथ व बद्रीनाथ धाम, जिम कॉर्बेट नेशनल पार्क',
    funFactEn: 'Jim Corbett Park is India’s oldest national park established in 1936!',
    funFactHi: 'जिम कॉर्बेट पार्क 1936 में स्थापित भारत का सबसे पहला राष्ट्रीय उद्यान है!',
    languageEn: 'Hindi, Garhwali',
    languageHi: 'हिन्दी, गढ़वाली',
    icon: '🏔️',
    color: '#0284c7',
    svgPath: ${JSON.stringify(svgPaths['ut'])},
    center: { x: 232, y: 175 }
  },
  {
    id: 'west-bengal',
    type: 'state',
    number: 28,
    nameEn: 'West Bengal',
    nameHi: 'पश्चिम बंगाल',
    code: 'WB',
    capitalEn: 'Kolkata',
    capitalHi: 'कोलकाता',
    zone: 'East',
    zoneHi: 'पूर्वी भारत',
    famousForEn: 'Sundarbans Tigers, Howrah Bridge, Rasgulla, Durga Puja',
    famousForHi: 'सुंदरबन रॉयल बंगाल टाइगर, हावड़ा ब्रिज, रसगुल्ला, दुर्गा पूजा',
    funFactEn: 'Sundarbans is the world’s largest mangrove forest delta!',
    funFactHi: 'सुंदरबन दुनिया का सबसे बड़ा मैंग्रोव वन डेल्टा है!',
    languageEn: 'Bengali',
    languageHi: 'बंगाली',
    icon: '🐅',
    color: '#10b981',
    svgPath: ${JSON.stringify(svgPaths['wb'])},
    center: { x: 412, y: 310 }
  }
];

export const INDIA_UTS: IndiaRegionItem[] = [
  {
    id: 'andaman-and-nicobar',
    type: 'ut',
    number: 1,
    nameEn: 'Andaman and Nicobar Islands',
    nameHi: 'अंडमान और निकोबार द्वीप समूह',
    code: 'AN',
    capitalEn: 'Port Blair',
    capitalHi: 'पोर्ट ब्लेयर',
    zone: 'Islands',
    zoneHi: 'द्वीप समूह',
    famousForEn: 'Cellular Jail, Radhanagar Beach, Coral Reefs',
    famousForHi: 'सेलुलर जेल (काला पानी), राधानगर बीच, मूंगा चट्टानें',
    funFactEn: 'India’s only active volcano is located on Barren Island in Andaman!',
    funFactHi: 'भारत का एकमात्र सक्रिय ज्वालामुखी अंडमान के बैरन द्वीप पर स्थित है!',
    languageEn: 'Hindi, English, Bengali',
    languageHi: 'हिन्दी, अंग्रेजी, बंगाली',
    icon: '🏝️',
    color: '#06b6d4',
    svgPath: ${JSON.stringify(svgPaths['an'])},
    center: { x: 521, y: 609 },
    isIslandOrTiny: true
  },
  {
    id: 'chandigarh',
    type: 'ut',
    number: 2,
    nameEn: 'Chandigarh',
    nameHi: 'चंडीगढ़',
    code: 'CH',
    capitalEn: 'Chandigarh',
    capitalHi: 'चंडीगढ़',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Rock Garden, Sukhna Lake, Le Corbusier City Planning',
    famousForHi: 'रॉक गार्डन, सुखना झील, ली कोर्बुज़िए द्वारा नियोजित शहर',
    funFactEn: 'Chandigarh serves as the joint capital of both Punjab and Haryana!',
    funFactHi: 'चंडीगढ़ पंजाब और हरियाणा दोनों राज्यों की संयुक्त राजधानी है!',
    languageEn: 'English, Punjabi, Hindi',
    languageHi: 'अंग्रेजी, पंजाबी, हिन्दी',
    icon: '🌹',
    color: '#a855f7',
    svgPath: ${JSON.stringify(svgPaths['ch'])},
    center: { x: 179, y: 160 },
    isIslandOrTiny: true
  },
  {
    id: 'dadra-and-nagar-haveli-and-daman-and-diu',
    type: 'ut',
    number: 3,
    nameEn: 'Dadra and Nagar Haveli and Daman and Diu',
    nameHi: 'दादरा और नगर हवेली एवं दमन और दीव',
    code: 'DN',
    capitalEn: 'Daman',
    capitalHi: 'दमन',
    zone: 'West',
    zoneHi: 'पश्चिमी भारत',
    famousForEn: 'Portuguese Forts, Devka Beach, Silvassa Gardens',
    famousForHi: 'पुर्तगाली किले, देवका बीच, सिलवासा उद्यान व जनजातीय संस्कृति',
    funFactEn: 'Merged into a single Union Territory in January 2020!',
    funFactHi: 'जनवरी 2020 में इन द्वीपों को मिलाकर एक केंद्र शासित प्रदेश बनाया गया!',
    languageEn: 'Gujarati, Hindi, English',
    languageHi: 'गुजराती, हिन्दी, अंग्रेजी',
    icon: '⚓',
    color: '#0284c7',
    svgPath: ${JSON.stringify(svgPaths['dn'] + ' ' + svgPaths['dd'])},
    center: { x: 80, y: 398 },
    isIslandOrTiny: true
  },
  {
    id: 'delhi',
    type: 'ut',
    number: 4,
    nameEn: 'Delhi (NCT)',
    nameHi: 'दिल्ली (राष्ट्रीय राजधानी क्षेत्र)',
    code: 'DL',
    capitalEn: 'New Delhi',
    capitalHi: 'नई दिल्ली',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Capital of India, Red Fort, Qutub Minar, India Gate',
    famousForHi: 'भारत की राजधानी, लाल किला, कुतुब मीनार, इंडिया गेट',
    funFactEn: 'New Delhi has been the capital of India since 1911!',
    funFactHi: 'नई दिल्ली 1911 से भारत की आधिकारिक राजधानी है!',
    languageEn: 'Hindi, English, Punjabi',
    languageHi: 'हिन्दी, अंग्रेजी, पंजाबी',
    icon: '🕌',
    color: '#ef4444',
    svgPath: ${JSON.stringify(svgPaths['dl'])},
    center: { x: 186, y: 210 },
    isIslandOrTiny: true
  },
  {
    id: 'jammu-and-kashmir',
    type: 'ut',
    number: 5,
    nameEn: 'Jammu and Kashmir',
    nameHi: 'जम्मू और कश्मीर',
    code: 'JK',
    capitalEn: 'Srinagar / Jammu',
    capitalHi: 'श्रीनगर / जम्मू',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Paradise on Earth, Dal Lake Shikara, Gulmarg Skiing',
    famousForHi: 'धरती का स्वर्ग, डल झील शिकारा, गुलमर्ग स्कीइंग, माता वैष्णो देवी',
    funFactEn: 'Kashmir is known worldwide as Paradise on Earth!',
    funFactHi: 'कश्मीर को पूरे विश्व में धरती का स्वर्ग कहा जाता है!',
    languageEn: 'Dogri, Kashmiri, Urdu',
    languageHi: 'डोगरी, कश्मीरी, उर्दू',
    icon: '❄️',
    color: '#0284c7',
    svgPath: ${JSON.stringify(svgPaths['jk'])},
    center: { x: 155, y: 68 }
  },
  {
    id: 'ladakh',
    type: 'ut',
    number: 6,
    nameEn: 'Ladakh',
    nameHi: 'लद्दाख',
    code: 'LA',
    capitalEn: 'Leh',
    capitalHi: 'लेह',
    zone: 'North',
    zoneHi: 'उत्तर भारत',
    famousForEn: 'Cold Desert, Pangong Tso Lake, Khardung La Pass',
    famousForHi: 'ठंडा मरुस्थल, पैंगोंग त्सो झील, खारदुंग ला दर्रा, बौद्ध मठ',
    funFactEn: 'Pangong Tso Lake in Ladakh is the highest saltwater lake in the world!',
    funFactHi: 'लद्दाख में पैंगोंग त्सो झील दुनिया की सबसे ऊंची खारे पानी की झील है!',
    languageEn: 'Ladakhi, Tibetan, English',
    languageHi: 'लद्दाखी, तिब्बती, अंग्रेजी',
    icon: '🏔️',
    color: '#6366f1',
    svgPath: ${JSON.stringify(svgPaths['jk'])},
    center: { x: 215, y: 55 }
  },
  {
    id: 'lakshadweep',
    type: 'ut',
    number: 7,
    nameEn: 'Lakshadweep',
    nameHi: 'लक्षद्वीप',
    code: 'LD',
    capitalEn: 'Kavaratti',
    capitalHi: 'कवारत्ती',
    zone: 'Islands',
    zoneHi: 'द्वीप समूह',
    famousForEn: '36 Coral Atolls, Lagoons, Marine Life',
    famousForHi: '36 प्रवाल द्वीप (Coral Reefs), पारदर्शी नीले लैगून, समुद्री जीवन',
    funFactEn: 'Lakshadweep is a group of 36 beautiful coral islands!',
    funFactHi: 'लक्षद्वीप 36 सुंदर मूंगा प्रवाल द्वीपों का समूह है!',
    languageEn: 'Malayalam, Jeseri',
    languageHi: 'मलयालम, जेसेरी',
    icon: '🏝️',
    color: '#14b8a6',
    svgPath: ${JSON.stringify(svgPaths['ld'])},
    center: { x: 99, y: 627 },
    isIslandOrTiny: true
  },
  {
    id: 'puducherry',
    type: 'ut',
    number: 8,
    nameEn: 'Puducherry',
    nameHi: 'पुडुचेरी',
    code: 'PY',
    capitalEn: 'Puducherry',
    capitalHi: 'पुडुचेरी',
    zone: 'South',
    zoneHi: 'दक्षिण भारत',
    famousForEn: 'French Quarter, Sri Aurobindo Ashram, Auroville',
    famousForHi: 'फ़्रेंच क्वार्टर, श्री अरबिंदो आश्रम, ऑरोविले, फ़्रांसीसी वास्तुकला',
    funFactEn: 'Puducherry was a French colony for nearly 300 years until 1954!',
    funFactHi: 'पुडुचेरी 1954 तक लगभग 300 वर्षों तक एक फ्रांसीसी उपनिवेश था!',
    languageEn: 'Tamil, French, English',
    languageHi: 'तमिल, फ्रांसीसी, अंग्रेजी',
    icon: '🏛️',
    color: '#ec4899',
    svgPath: ${JSON.stringify(svgPaths['py'])},
    center: { x: 268, y: 546 },
    isIslandOrTiny: true
  }
];

export const ALL_INDIA_REGIONS: IndiaRegionItem[] = [...INDIA_STATES, ...INDIA_UTS];
`;

fs.writeFileSync('/workspace/src/data/indiaData.ts', content);
console.log('Successfully written indiaData.ts');
